"use client";

import { useState, type RefObject } from "react";
import { toPng } from "html-to-image";
import { Share2, Download, FileText, Loader2 } from "lucide-react";

interface ReportCardActionsProps {
  cardRef: RefObject<HTMLDivElement | null>;
  filename: string;
}

type Busy = "share" | "png" | "pdf" | null;

async function captureCard(node: HTMLDivElement): Promise<{ blob: Blob; dataUrl: string }> {
  const dataUrl = await toPng(node, {
    pixelRatio: 2,
    backgroundColor: "#0a0a0a",
    cacheBust: true,
  });
  const res = await fetch(dataUrl);
  const blob = await res.blob();
  return { blob, dataUrl };
}

function triggerDownload(blob: Blob, name: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = name;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 0);
}

function loadImage(src: string): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => resolve(img);
    img.onerror = reject;
    img.src = src;
  });
}

export default function ReportCardActions({ cardRef, filename }: ReportCardActionsProps) {
  const [busy, setBusy] = useState<Busy>(null);
  const [error, setError] = useState<string | null>(null);

  async function handleShare() {
    if (!cardRef.current) return;
    setError(null);
    setBusy("share");
    try {
      const { blob } = await captureCard(cardRef.current);
      const file = new File([blob], `${filename}.png`, { type: "image/png" });

      const nav = navigator as Navigator & {
        canShare?: (data: { files?: File[] }) => boolean;
        share?: (data: { files?: File[]; title?: string; text?: string }) => Promise<void>;
      };

      if (nav.canShare?.({ files: [file] }) && nav.share) {
        await nav.share({
          files: [file],
          title: "BigMarkt Report",
          text: "My BigMarkt report — via BigMarkt",
        });
      } else if (navigator.clipboard && "write" in navigator.clipboard) {
        await navigator.clipboard.write([new ClipboardItem({ "image/png": blob })]);
        setError("Copied to clipboard");
      } else {
        triggerDownload(blob, `${filename}.png`);
      }
    } catch (e) {
      console.error("share failed", e);
      setError(e instanceof Error ? e.message : "Share failed");
    } finally {
      setBusy(null);
    }
  }

  async function handleDownloadPng() {
    if (!cardRef.current) return;
    setError(null);
    setBusy("png");
    try {
      const { blob } = await captureCard(cardRef.current);
      triggerDownload(blob, `${filename}.png`);
    } catch (e) {
      console.error("download png failed", e);
      setError(e instanceof Error ? e.message : "Download failed");
    } finally {
      setBusy(null);
    }
  }

  async function handleDownloadPdf() {
    if (!cardRef.current) return;
    setError(null);
    setBusy("pdf");
    try {
      const { dataUrl } = await captureCard(cardRef.current);
      const img = await loadImage(dataUrl);

      const { jsPDF } = await import("jspdf");
      const pdf = new jsPDF({ orientation: "landscape", unit: "pt", format: "a4" });
      const pageW = pdf.internal.pageSize.getWidth();
      const pageH = pdf.internal.pageSize.getHeight();

      // Fit the image within ~80% of the page while preserving aspect ratio.
      const maxW = pageW * 0.8;
      const maxH = pageH * 0.8;
      const aspect = img.width / img.height;
      let drawW = maxW;
      let drawH = drawW / aspect;
      if (drawH > maxH) {
        drawH = maxH;
        drawW = drawH * aspect;
      }
      const x = (pageW - drawW) / 2;
      const y = (pageH - drawH) / 2;

      pdf.setFillColor(10, 10, 10);
      pdf.rect(0, 0, pageW, pageH, "F");
      pdf.addImage(dataUrl, "PNG", x, y, drawW, drawH);

      pdf.setFontSize(9);
      pdf.setTextColor(163, 163, 163);
      pdf.text(
        "Generated by BigMarkt — journal.bigmarkt.co",
        pageW / 2,
        pageH - 18,
        { align: "center" },
      );

      pdf.save(`${filename}.pdf`);
    } catch (e) {
      console.error("download pdf failed", e);
      setError(e instanceof Error ? e.message : "PDF generation failed");
    } finally {
      setBusy(null);
    }
  }

  const disabled = busy !== null;

  return (
    <div className="space-y-2">
      <div className="flex flex-wrap gap-2 justify-center">
        <button
          type="button"
          onClick={handleShare}
          disabled={disabled}
          className="flex items-center justify-center gap-2 rounded-md border border-gold bg-bg px-4 py-2 font-display text-sm tracking-widest text-gold transition hover:bg-gold hover:text-black disabled:opacity-50"
        >
          {busy === "share" ? <Loader2 className="h-4 w-4 animate-spin" /> : <Share2 className="h-4 w-4" />}
          SHARE
        </button>
        <button
          type="button"
          onClick={handleDownloadPng}
          disabled={disabled}
          className="flex items-center justify-center gap-2 rounded-md border border-gold bg-bg px-4 py-2 font-display text-sm tracking-widest text-gold transition hover:bg-gold hover:text-black disabled:opacity-50"
        >
          {busy === "png" ? <Loader2 className="h-4 w-4 animate-spin" /> : <Download className="h-4 w-4" />}
          DOWNLOAD PNG
        </button>
        <button
          type="button"
          onClick={handleDownloadPdf}
          disabled={disabled}
          className="flex items-center justify-center gap-2 rounded-md border border-gold bg-bg px-4 py-2 font-display text-sm tracking-widest text-gold transition hover:bg-gold hover:text-black disabled:opacity-50"
        >
          {busy === "pdf" ? <Loader2 className="h-4 w-4 animate-spin" /> : <FileText className="h-4 w-4" />}
          DOWNLOAD PDF
        </button>
      </div>
      {error ? <p className="text-center text-xs text-muted">{error}</p> : null}
    </div>
  );
}
